name: Greenframe Analysis
on: [push]
jobs:
  greenframeci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all the git history
      - run: curl https://assets.greenframe.io/install.sh | bash
      # Start your application here
      # - name: scenario
      - run: greenframe analyze scenario.js https://www.google.com/ --commitId "SHA1_COMMIT_ID"
        env:
          GREENFRAME_SECRET_TOKEN: fd63705e31f40925032aedbc02ff1f231c207736
