name: Greenframe Analysis
on: [push]
baseURL: https://www.google.com/
projectName: Demo
scenarios: 
    - path: ./scenario.js
      name : My first scenario
jobs:
  greenframeci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all the git history
      - run: curl https://assets.greenframe.io/install.sh | bash
      - run: ./scenario.js
      # Start your application here
      - run: greenframe analyze
        env:
          GREENFRAME_SECRET_TOKEN: fd63705e31f40925032aedbc02ff1f231c207736
